// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CutStorm - Editor de Vídeos Inteligente",
  description: "Transforme vídeos longos em cortes virais prontos para redes sociais usando inteligência artificial. Upload direto ou importação do YouTube com validação Creative Commons.",
  keywords: "editor de vídeo, IA, cortes virais, redes sociais, YouTube, TikTok, Instagram, shorts",
  authors: [{ name: "CutStorm Team" }],
  creator: "CutStorm",
  publisher: "CutStorm",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL('https://cutstorm.app'),
  openGraph: {
    title: "CutStorm - Transforme vídeos longos em cortes virais com IA",
    description: "Editor de vídeos inteligente que cria cortes virais automaticamente. Upload direto ou importação do YouTube.",
    url: 'https://cutstorm.app',
    siteName: 'CutStorm',
    locale: 'pt_BR',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'CutStorm - Editor de Vídeos Inteligente',
    description: 'Transforme vídeos longos em cortes virais com IA',
    creator: '@cutstorm',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}